### ISSUE TITLE
dynamic serviceUrl?

### ISSUE THREAD

**Issue by yairEO** [devbridge/jQuery-Autocomplete#141]
how can I use a dynamic `serviceUrl` which keeps changing? I want to use google suggest API:
`"http://google.com/complete/search?output=toolbar&q=" + TEXT`

**Comment by mgntrn** [comment]
@yairEO Any idea on how to use the Google API? I've been looking for a solution for a while now, but can't get it to work with jsonp either. Hopefully there is a possibility to use the Google Autocomplete API with jQuery Autocomplete, because I've spent days developing an application in which multiple search boxes work together.

**Comment by sevilyilmaz** [comment]
@yairEO one way to use Google is to create a server-side proxy. You can call your service and your service calls Google then your server returns the Google's response.

But if your application sends a lot of request to Google, you request can be blocked by Google.

**Comment by mgntrn** [comment]
That's how I 'solved' this for now and it works perfectly, but how do I know they don't block me? I can't find anything about this kind of usage of the API, so I'm not sure whether this method is allowed or not.

**Comment by sevilyilmaz** [comment]
I'm not sure it is allowed or not. Either way you need to reference Google in your search results like this: "Powered by Google". It was just a general "solution" came to my mind  for cross-origin. I didn't think legal issues.

You can check https://developers.google.com/custom-search/json-api/v1/overview as well.

Lets not dwell on this topic. Because this isn't an issue of this plugin :)
