### ISSUE TITLE
a triggerSelectOnValidInput bug

### ISSUE THREAD

**Issue by dmfeng** [devbridge/jQuery-Autocomplete#281]
$input.autocomplete({
    triggerSelectOnValidInput:true,
    lookup : [{value:'qwer',data:{id:1}},{value:'qwer',data:{id:2}}],
    onSelect:function(ret){
        console.log(ret);
    }
})

if( $input.val() == 'qwer' )
id:1 selected

but not only one

**Comment by EricAlla** [comment]
Fender, did you try to set triggerSelectOnValidInput to false? In my case, it triggerred an unexpected behaviour that I explained here https://github.com/devbridge/jQuery-Autocomplete/issues/307. Do you also get the same strange behaviour?

**Comment by Fender123** [comment]
@EricAlla no it is working for me

**Comment by EricAlla** [comment]
Hummm, interesting... So the issue comes from my configuration or jquery version as I took a basic example with bare minimum code.
thanks for testing

--------------------------------------------
En date de : Ven 30.1.15, Fender123 <notifications@github.com> a écrit :

 Objet: Re: [jQuery-Autocomplete] a triggerSelectOnValidInput bug (#281)
 À: "devbridge/jQuery-Autocomplete" <jQuery-Autocomplete@noreply.github.com>
 Cc: "EricAlla" <eric_allal@yahoo.fr>
 Date: Vendredi 30 janvier 2015, 9h27
 
 @EricAlla no it is
 working for me
 
 —
 Reply to this email directly or view
 it on GitHub.
