### ISSUE TITLE
Onchange and onSelect are conflicting

### ISSUE THREAD

**Issue by vsdotnetguy** [devbridge/jQuery-Autocomplete#372]
First off, we love the autocomplete you've created.  It is very useful, thank you.

However, we need to allow our users to input values directly without selecting as well as select from autocomplete suggestion(s).

We know the onchange event can be used to capture and process the input element text when the user does not select.  However, when the user does select, the events are triggered in the order of onchange first followed by onSelect.  When inside our onchange event the value of the input element only includes what the user typed not the selected suggestion text.  In this case, the onchange event does not know whether to process the input element text as-is or whether the user selected and what the suggestion text is.  Basically, we need the onSelect event to fire first so the onchange event input element text is the actual selected suggestion not what the user typed.  Is this scenario possible with your Autocomplete?

We realize your Autocomplete doesn't directly support onchange like the jquery.UI autocomplete does but can you help give us some direction on how to handle this?  Would a setTimeout be in order here?

Thanks in advance...
Bob Baldwin
aka VSDotNetGuy

**Comment by tkirda** [comment]
Not sure I understand objective here. You can listen for `change` event:

    $('#autocomplete').on('input', function () { console.log(this.value); })

Then `onSelect` from autocomplete should fire later. It probably also depends on in what order listeners were attached. But you should be able to accomplish it. `setTimeout` in the on select would work, then it would be later for sure.

**Comment by vsdotnetguy** [comment]
Hi Tomas,

Let me try this one more time...

We are experiencing the same issue as the poster in the following old post:
https://github.com/devbridge/jQuery-Autocomplete/issues/6

However, since you've removed the onchange event built into your autocomplete, we cannot rely on the data value being passed as -1 when a suggestion is not selected like the poster was able to use.

Therefore, we've issued a jquery "on" event for when the input element changes and it is working but unfortunately, not very well in conjunction with Devbridge's Autocomplete.

We're still experiencing the problem like this:
1. The user types 4 characters and several suggestions are rendered.
2. The user "clicks" on a suggestion that is 10 characters long.
3. The jquery "on" event fires FIRST and knows the input value as 4 characters and does a lookup based on the 4 characters because it does not know the user selected a suggestion.
4. However, the user does not want the 4 characters but the 10 character value they "clicked" that will be passed into the autocomplete onselect event.

How can we tell inside the jquery "on" change event that a suggestion was "clicked" so we can bypass processing and let the autocomplete onselect process the clicked 10 character suggestion?

Again, we must support both onchange and onselect as many users type the entire value and never select a value from the autocomplete but press enter or tab key to move to next input element.

Also, we really do not want to use a setTimeout as this is often client browser performance sensitive and may not always work.

Please let me know if this more clearly describes the issue.  Hopefully you can help us further so we can continue to use Devbridge's autocomplete.

Can you consider adding back in the onchange handler?

Thanks in advance...Bob Baldwin
aka VSDotNetGuy

**Comment by flyingtime** [comment]
```javascript
function IsShowSuggestions() {
        var found = false;
        $("div.autocomplete-suggestions").each(function () {
            if ($(this).css("display") != 'none') {
                found = true;
                return false;
            }
        })
        return found;
}

//autocomplete.onSelect
onSelect:function(){
      if(!IsShowSuggestions()) submit();
}
//input.onChange
onChange:function(){
      if(!IsShowSuggestions()) submit();
}
```
if found div.autocomplete-suggestions display do not submit

**Comment by tkirda** [comment]
I think we can add onChange handler. Question is when it should actually fire and what exactly it means? Any time value changes regardless if it was user selected or set by the script?

**Comment by flyingtime** [comment]
this onChange only catch the value like input onChange not like oninput or onpropertychange. i’am sorry for my bad english…在 2016年8月15日，上午10:20，Tomas Kirda <notifications@github.com> 写道：I think we can add onChange handler. Question is when it should actually fire and what exactly it means? Any time value changes regardless if it was user selected or set by the script?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/devbridge/jQuery-Autocomplete","title":"devbridge/jQuery-Autocomplete","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/devbridge/jQuery-Autocomplete" class="">https://github.com/devbridge/jQuery-Autocomplete</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tkirda in #372: I think we can add onChange handler. Question is when it should actually fire and what exactly it means? Any time value changes regardless if it was user selected or set by the script?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/devbridge/jQuery-Autocomplete/issues/372#issuecomment-239716617" class="">https://github.com/devbridge/jQuery-Autocomplete/issues/372#issuecomment-239716617</a>"}}}
