### ISSUE TITLE
Can not have 2 separate instances of autocomplete active at the same time

### ISSUE THREAD

**Issue by nexus-uw** [devbridge/jQuery-Autocomplete#384]
Hello,

I ran into a problem where I wanted to have 2 autocomplete fields on the same page but for them to hit different endpoints for matches. I noticed that while both input fields were firing search requests, they were directed to the default url (```...?query=input``` ), and that my min character limit was not being enforced.

It would appear that once you attach autocomplete to a second element, all instances have their options overwritten.

**Comment by tkirda** [comment]
Something is definitely not right in your setup. Every autocomplete is separate instance and there are no shared variables, at least there shouldn't be. I can not help you unless you provide sample where this can be reproduced.

**Comment by SgtOddball** [comment]
Are you setting running a loop and applying the autocomplete to each field or applying the same autocomplete to all fields? Could it be that only one instance of autocomplete is being added to the page and that it's that which is firing for both? 

Also have you tried using using one or the other (rather than both instances) to make sure it's working correctly when applied individually?

I agree with @tkirda though because I've got a page with 4 different auto completes and they all work independently without issue.

**Comment by nexus-uw** [comment]
Hi tkirda & SgtOddball,

It has been a while and I just ended up going with jquery ui for the project. But from what I remember, I was trying something like this
```javascript
function addAutoComplete(selector, endpoint){
 $('#'+selector).autocomplete({
    serviceUrl: '/some/uri?endpoint='+endpoint,
   ....
 });
}
addAutoComplete('ele1','names');
addAutoComplete('ele2','places);
```

**Comment by SgtOddball** [comment]
Humm I don't see why that shouldn't work, admittedly I went a different route namely doing an each loop instead of having a separate function. ie.

```javascript
$('input[data-flag="complete"]').each(function(){
    $(this).autocomplete({
        paramName: $(this).attr("name")+'Complete',
        ....
    })
})
```
Did you check to see what the DOM was saying in regards to the elements you applied the autocomplete to?

**Comment by nexus-uw** [comment]
Since I am not finding the time to responsibility debug this issue these days, Im just going to close this issue. Thanks for help everyone.
