### ISSUE TITLE
html entities problem

### ISSUE THREAD

**Issue by yehudah** [devbridge/jQuery-Autocomplete#385]
Hello,

When my suggestions have double quotes the script convert the visual char to the releavent html entities.

I searched and didn't found someone complain on the same issue and that very odd.

I'm using jquery 1.11.3 and the latest plugin release.
the website is in hebrew.

Thanks.

**Comment by tkirda** [comment]
Some HTML entities are escaped, so that it would not affect HTML. But this should not have side effects. Here is code snippet that makes string html safe:

        var htmlSafeString = suggestion.value
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');


I just tested sample with quotes, and quotes are displayed normally in the suggestion list.

**Comment by Carpetsmoker** [comment]
Hi, I seem have the same problem, the issue is the search highlighting is applied to the HTML entities, so for example searching for `g` gives us this HTML:

    Mar<strong>t</strong>in &l<strong>t</strong>;mar<strong>t</strong>in@arp242.ne<strong>t</strong>&g<strong>t</strong>;

This is done in the `Autocomplete.formatResult` function. `&l<strong>t</strong>;` is obviously wrong. 

Here's a patch which sort of fixes it, we escape HTML entities *after* adding the strong tags, and then un-escape the strong tags again. It's not a pretty solution, but in my case it's "good enough", and my mind doesn't offer a better solution right this minute:

	--- /home/martin/jquery.autocomplete.js 2015-07-29 13:43:50.658932570 +0200
	+++ contrib/jquery.autocomplete.js      2015-07-29 13:51:17.808507767 +0200
	@@ -127,15 +127,16 @@
		$.Autocomplete = Autocomplete;
	
		Autocomplete.formatResult = function (suggestion, currentValue) {
	-        var htmlSafeString = suggestion.value
	-            .replace(/&/g, '&amp;')
	-            .replace(/</g, '&lt;')
	-            .replace(/>/g, '&gt;')
	-            .replace(/"/g, '&quot;');
	
			var pattern = '(' + utils.escapeRegExChars(currentValue) + ')';
	
	-        return htmlSafeString.replace(new RegExp(pattern, 'gi'), '<strong>$1<\/strong>');
	+        return suggestion.value
	+          .replace(new RegExp(pattern, 'gi'), '<strong>$1<\/strong>')
	+          .replace(/&/g, '&amp;')
	+          .replace(/</g, '&lt;')
	+          .replace(/>/g, '&gt;')
	+          .replace(/"/g, '&quot;')
	+          .replace(/&lt;(\/?strong)&gt;/g, '<$1>');
		};
	
		Autocomplete.prototype = {
