### ISSUE TITLE
Bug: In some cases the suggestions dropdown doesn't hide on blur

### ISSUE THREAD

**Issue by majiangl** [devbridge/jQuery-Autocomplete#447]
You can recur the bug by following steps:
1. Active auto complete, keep the dropdown show.
2. Find another input, get mouse down and hold.
3. Move mouse out of the input and mouse up.

I have found the reason. When the autocomplete input blurs, `enableKillerFn` function is called which binds a click event to document. When there is a click event after blur, It's always right. But as illustrated above, sometimes there won't have a click event.

I have fixed this problem by replace click event with mouseup event, along with another small modification. I think the mechanism here is not so good. I wonder if you can refer to the jquery ui autocomplete to make the dropdown hide just on a mousedown.

Wish better.

**Comment by Sigma-90** [comment]
I have similar issues and it's quite the dealbreaker. The element blurs correctly when I use the tab key to navigate to the next input element, but if I use the mouse to click on any other form element on the page, the suggestions box stays open. This is especially problematic when the clicked element is another autocompleter, as this will result in multiple suggestion lists overlapping each other.

To prevent that, I tried to close them manually when another element gets the focus by defining an onFocus event for all elements in the form where I would loop through all elements with an autocompleter and called .autocompleter('hide') on them. Except for the case that the focused element is an autocompleter itself, then the loop skips over it to prevent that the suggestion list for the focused element is closed immediately after being openend. And yet that seems to exactly what happens, despite that precaution, resulting in no suggestion boxes being shown anywhere on the page at all, which leads me to believe that the hide function actually hides all suggestion boxes on a page and not just the one bound to the element the function is called upon. I guess that's probably so because it was never intended that multiple suggestion boxes could be open at the same time anyway, but as long as the previously reported bug remains, that can indeed happen.
