### ISSUE TITLE
Select list should be responsive

### ISSUE THREAD

**Issue by stratboy** [devbridge/jQuery-Autocomplete#548]
Hi! If the select list is shown and you narrow the window size to a smaller size than the select itself (for ex. desktop > smartphone), then the select will be out of the window (too big). It won't resize with the rest of the content. Solutions could be at least 2:
- Recalculate select width on window resize.
- Add an option to simply disable the hard-coded width calculation, to let the more 'advanced' coder to simply use css to add responsive capabilities.

Thank you for your work, regards

**Comment by tkirda** [comment]
PR is welcome.

**Comment by andyford** [comment]
I found this page because I was having a similar issue. What worked for me was to set the 'appendTo' config param to the parent/ancestor element of the input that was getting the autocomplete. (you may have to add a wrapping element in your HTML if you don't have one that already works for this purpose)

```
var inputElem = $('#some-input');
inputElem.autocomplete({
  appendTo: inputElem.parents('.class-on-parent') // this might be '.input-group' if you're using Bootstrap
});
```

With that in place, you can set the parent element's position to 'relative' in the CSS, then set min-width and/or max-width on the corresponding `.autocomplete-suggestions` element(s).

Might not work for all situations, but it did work out in my particular situation.
