### ISSUE TITLE
Click on suggetstion list didn't fill input

### ISSUE THREAD

**Issue by koekaverna** [devbridge/jQuery-Autocomplete#667]
Hello, when im select item with keybord it fill input.
But if i click on it nothing happens

demo: https://codepen.io/oshihirii/pen/EvMjZm

**Comment by tkirda** [comment]
It seems to work for me. Which example did not work?

**Comment by koekaverna** [comment]
It's very strange, but it work for me now too. It seems to be a browser/os bug, and it gone after reboot.

**Comment by thetuningspoon** [comment]
@koekaverna  The problem occurs when you hold down the mouse button for longer than an instant. I have been experiencing this same issue and finally figured out what it was. This is happening for me in Chrome.

**Comment by thetuningspoon** [comment]
Just looked into this and the problem is that the click event that is supposed to cancel the blurTimeoutId timeout does not fire until after the user lets up on the mouse button, so the clearTimeout never fires. I tried switching the event to mousedown instead, but then blurTimeoutId was not defined yet. My solution was to use mousedown as well as set a short timeout before clearing the other timeout.

A simpler method would be to just check which element was clicked in the first place and never set the timeout at all, but I wasn't sure how to do that the way that the plugin is currently structured.

Anyway, here was my fix (line 201): 

`container.on('mousedown.autocomplete', function () {
                setTimeout(function() {
                    clearTimeout(that.blurTimeoutId);
                }, 100);
            });
`

**Comment by Dorothee47** [comment]
I would like to solve this problem, but I am scared to change the original code of devbridge autocomplete 1.4.9.
Is there a posibility to solve this problem in a more official way?
Should I wait until the next release? How long would that be?
Thank you very much for a helpfull answer.
