### ISSUE TITLE
Error with jQuery 3.4.1

### ISSUE THREAD

**Issue by thomasdarde** [devbridge/jQuery-Autocomplete#759]
Since updating to jQuery 3.4.1 I have this error :

```
TypeError: undefined is not a function (near '...$(".js-search-autocomplete").autocomplete...')
```

The element is present in the dom, the line referenced for jQuery is 3343

**Comment by EECOLOR** [comment]
This is most likely caused by your build holding on to another version of jquery.

The `package.json`  dependends on a variable version of jquery. Package managers like `yarn` do not understand this very well. So when you update `jquery` it will keep the original dependency for `devbridge-autocomplete`.

Solution: remove the `yarn.lock` file and reinstall.

You can use `yarn why jquery` to make sure `devbride-autocomplete` points to the same version as your main build.

**Comment by thomasdarde** [comment]
You were right, I had to edit the `yarn.lock` file..
Very weird that it did not respect my dependency tree
